### PR TITLE
Publications

### PR DESCRIPTION
**Pull request by ashtonmv**
One way to host publications built on pyiron would be to add them as blog posts, like I did here for @freyso's generalized dipole correction PRB. New papers should be added under _posts, with the naming convention YYYY-MM-DD-paper-name.md, where the date should be that of the paper's publication.

If we want to use this strategy for managing publications, we should keep this PR unmerged until we have a few more papers with mybinders to link, as we discussed last week in the pyiron meeting.

Screen Shot 2020-08-31 at 11 02 50

### CODE REVIEW

**Comment by liamhuber** [comment]
A second paper is added, but still missing the mybinder link.

I'm afraid I don't know how to setup mybinder stuff yet and don't expect to have time to figure it out inside the next week or two. I'm attaching the relevant notebook here in case we want to go public with this branch before I get to it and someone else wants to set it up.

(of course it's ipynb not pptx, I'm just getting around the upload format constraints...)
[MolecularDynamics-MonteCarlo_demo.pptx](https://github.com/pyiron/pyiron.github.io/files/5169290/MolecularDynamics-MonteCarlo_demo.pptx)

**Comment by ashtonmv** [comment]
Thanks Liam! This looks good. I can probably make a mybinder for the notebook you attached. If I can get it set up, would you have time just to test it (in the coming days/weeks) to make sure all the outputs make sense?

**Comment by liamhuber** [comment]
@ashtonmv wonderful, thanks for getting that set up so quickly! And yeah, I suppose actually including the GB structure file would help :sweat_smile:
[S5_s001_n210_r1011.pptx](https://github.com/pyiron/pyiron.github.io/files/5170576/S5_s001_n210_r1011.pptx)

I will definitely manage to double check the output next week. Thanks again!

**Comment by jan-janssen** [comment]
In addition to publications which use pyiron we should also list the pyiron paper on this page, because we currently do not have it on the website.

**Pull request merged**
