### PR TITLE
Mybinder embed

### PR DESCRIPTION
**Pull request by ashtonmv**
This is not yet ready to go, but I thought after today's meeting it would be cool if users had the option to actually edit and run the code snippets directly on pyiron.org without leaving to go to mybinder. Apparently it's possible with [Juniper](https://github.com/ines/juniper):

```javascript
new Juniper({
    repo: 'pyiron/pyiron',  // the mybinder server to link
    theme: 'monokai',  // color + syntax highlighting
    isolateCells: false,  // share variables between cells
    msgLoading: “ “
})
```

mybinder_embed

Right now I have the website set up to convert all python-based code snippets into runnable jupyter cells. I embedded notebooks into our publication pages and getting-started. I wrote more details about how it all works in the README.

This might be overkill, and obviously there are limitations that I'm looking into. But if we can pull it off, then we would just have to carefully decide what the default code should be in each cell on the homepage. The featured snippets are controlled in the files
```bash
_includes/
  generic_interface.md
  infrastructure.md
  extendability.md
```

### CODE REVIEW

**Comment by ashtonmv** [comment]
After playing with it quite a bit, I’m very impressed with Juniper. It’s pretty stable and the only drawback I see is that I don’t think it can serve NGLView widgets. I haven’t tried very hard but I’m skeptical that it’s possible.

However, in my mind it’s still an open question whether or not we even want to have something as “non-fail-proof” as runnable python lines right in the middle of our homepage. Maybe we can discuss this in Friday’s meeting.

**Comment by jan-janssen** [comment]
That is a great idea and I directly see the benefit how we could combine it with the tutorial video, splitting it in smaller parts and allowing the user to execute the code right next to the person speaking, like it is done here https://course.spacy.io/en/ by the way I like the https://spacy.io in general so maybe that is something we can use as inspiration. 

Still for the website I have a two questions about the mybinder integration: 

- How long does it take to lead? Unfortunately starting a regular session on mybinder is rather slow in particular with the pyiron container which is packed with simulation codes. 
- Are the cells connected? On the one hand this would have the advantage that the project only needs to be defined once. On the other hand if the second cell is executed before the first cell the user gets an error.

**Comment by ashtonmv** [comment]
> How long does it take to lead? Unfortunately starting a regular session on mybinder is rather slow in particular with the pyiron container which is packed with simulation codes.

It can take a while on the first load (you can try it out [here](https://www.michael-ashton.com/pyiron_beta_site/)), because we're using the full-fledged pyiron instance. If we want to implement this, I would suggest creating a separate lightweight mybinder just for the website front page that loads as quickly as possible. Also, the nice thing about Juniper is that it allows for persistent MyBinder connections. So once you've loaded it the first time you can travel around our site and just re-use the same Mybinder instance.

> Are the cells connected? On the one hand this would have the advantage that the project only needs to be defined once. On the other hand if the second cell is executed before the first cell the user gets an error.

Yes they are connected, but if we ever want to "disconnect" them for a given page Juniper allows for this:

```javascript
new Juniper({
    isolateCells: true,  // DON'T share variables between cells
    .
    .
})
```

**Comment by ashtonmv** [comment]
> by the way I like the https://spacy.io in general so maybe that is something we can use as inspiration.

Check out https://github.com/ines/course-starter-python. @Ines basically made their course into a template! I agree this would be very cool to create and host. Even cooler if we set up our own BinderHub backend.

**Comment by jan-janssen** [comment]
Suggestion for code blocks: 
```
from pyiron import Project                        # Import Project object 
pr = Project("demonstration")                     # Create a project/folder 
structure = pr.create_ase_bulk("Al")              # Create an aluminium bulk structure
for job_type in ["GpawJob", "Lammps", "Sphinx"]:  # Iterate over simulation codes
    job = pr.create_job(                          # Create a job object
        job_type=job_type, 
        job_name=job_type
    )
    job.structure = structure                     # assign the structure 
    job.run()                                     # Execute the calculation locally
```
```
table = pr.create_table()                         # Create analysis object 
table.add.get_energy_tot                          # Define analysis functions 
table.add.get_volume                              # get the volume and total energy

def get_code_type(job):                           # Define custom analysis function
    return job.__name__                           # Get the job type of the calculation

table.add["job_type"] = get_code_type             # Add custom analysis function
table.run()                                       # Execute the analysis 
print(table.get_dataframe())                      # Results are summarized in DataFrame
```
```
job = pr.create_job(                              # Create a job object
    job_type=pr.job_type.Sphinx,                  # Use project to select job type 
    job_name="spx_hpc"                            # Set job name
)
job.structure = structure                         # Assign atomistic structure
print(job.server.list_queues())                   # List of available queues
# job.server.queue = "cm"                         # Select a queue 
job.server.cores = 4                            # Set number of cores
job.server.run_time = 1000                      # Set run time 
job.run()                                         # The job is executed on the HPC cluster
```

**Comment by jan-janssen** [comment]
@ashtonmv Does it make sense to close this pull request and start a new one based on the current master once nbjuniper is ready?

**Comment by ashtonmv** [comment]
Yes it does- I was just thinking the same thing.

This is be a real achievement- we'll have no open issues or PR's at least for a moment or two 😄

**Pull request closed without merging**
