### PR TITLE
Shiny landing page

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by ashtonmv** [comment]
Thanks @jan-janssen! Please feel free to make liberal changes to anything and everything I wrote.

IMO, an important next step could be to set up a support email. Right now, the contact form will send messages to support@pyiron.org, and I'm not sure if that address exists. I think even a simple address like pyironsupport@gmail.com would work, as long as someone monitors it.

**Comment by jan-janssen** [comment]
At least we have pyiron@mpie.de that is a old mailing list and I believe it now reaches Joerg, @sudarsan-surendralal and me. I have to talk to ulrich to see if we can get an support@pyiron.org Email address.

**Comment by samwaseda** [comment]
I see that the mobile version is not well formatted. Is it possible to write a different CSS?

And it would be nice to create a QR code at some point, not only for the external people but also for us to have a template whenever we give a presentation outside etc.

**Comment by ashtonmv** [comment]
Thanks @samwaseda, I fixed the two bugs I could find for the mobile site, but I'm only able to test on my iphone so if you still see other issues for other devices please let me know.

As for the QR code, it seem you can [make on on-the-fly](https://www.qr-code-generator.com) for pyiron.org or any url.

**Comment by samwaseda** [comment]
Well the thing is there are also fancy QR codes with a logo. Maybe we can make one like that and put it on the website?

**Comment by ashtonmv** [comment]
That's cool, I didn't know about those. I just added one to the website under "About" that you should be able to download.

**Pull request merged**
