### PR TITLE
Remove '-c conda-forge'

### PR DESCRIPTION
**Pull request by ashtonmv**
New homepage with compact conda installation command

```sh
conda install pyiron
```

### CODE REVIEW

**Comment by jan-janssen** [comment]
Sorry this was confusing - We still need the `-c conda-forge` part.

**Comment by jan-janssen** [comment]
I just meant that we no longer need to the do:

```
import pyiron
pyiron.install() 
exit()
```

to create a `.pyiron` file and configure pyiron.

**Comment by ashtonmv** [comment]
Oh sorry I guess I got too excited 😆

**Review by jan-janssen — COMMENTED** [review]
I guess my statement in the pyiron meeting was misleading.

**Pull request closed without merging**
